//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGINpage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Table
    {
        public decimal id_Employé { get; set; }
        public string Nom_employé { get; set; }
        public string Adresse { get; set; }
        public Nullable<decimal> Salaire { get; set; }
        public string Rôle { get; set; }
    }
}
